version: '3.8'
services:
  frontend:
    build: 
      context: ./frontend
    image: bhargavasai9999/e-attendance-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  QRCode:
    build: 
      context: ./QRCode
    image: bhargavasai9999/e-attendance-qrcode-page
    ports:
      - "3001:3001"
    depends_on:
      - backend
  studentApp:
    build:
      context: ./studentApp
    image: bhargavasai9999/e-attendance-studentapp
    ports:
      - "4000:4000"
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend
    image: bhargavasai9999/e-attendance-backend
    ports:
      - "5000:5000"
    env_file:
      - /backend/.env