version: '3.8'
services:
  frontend:
    build: 
      context: ./frontend
    image: bhargavasai9999/e-attendance-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build: 
      context: ./backend
    image: bhargavasai9999/e-attendance-backend
    ports:
      - "5000:5000"
    env_file:
      - /backend/.env