#setup node Environment
FROM node:21.5.0-alpine

#Working Directory
WORKDIR /e-attendance/backend

#Copy Package.json File 

COPY package.json /e-attendance/backend/
RUN npm install --verbose

COPY . .

EXPOSE 5000

#Run Your node application

CMD [ "npm","run","dev" ]
